version: "3.3"
services:
  flask-app:
    image: dylantodd01/flask-app:latest
    build: ./
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
    - flask-app